#!/bin/sh

# script/bootstrap: Set up project dependencies

set -e

cd "$(dirname "$0")/.."

echo "Installing dependencies..."

npm install

cd server
npm install

cd ..

cd client
npm install

cd ..

cd scanner
npm install
